<a href="https://colab.research.google.com/github/vijaykumarharakuni/mllearning/blob/main/PCA_Winedataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
data=pd.read_csv('Wine_data.csv')

In [ ]:
pd

<module 'pandas' from 'C:\\Users\\vijay\\anaconda3\\Lib\\site-packages\\pandas\\__init__.py'>

In [ ]:
data

Label  Alcohol  Malic Acid   Ash  Alcalinity of ash   Magnesium  \
0        1    14.23        1.71  2.43                15.6        127   
1        1    13.20        1.78  2.14                11.2        100   
2        1    13.16        2.36  2.67                18.6        101   
3        1    14.37        1.95  2.50                16.8        113   
4        1    13.24        2.59  2.87                21.0        118   
..     ...      ...         ...   ...                 ...        ...   
173      3    13.71        5.65  2.45                20.5         95   
174      3    13.40        3.91  2.48                23.0        102   
175      3    13.27        4.28  2.26                20.0        120   
176      3    13.17        2.59  2.37                20.0        120   
177      3    14.13        4.10  2.74                24.5         96   

     Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
0             2.80        3.06                  0.28             2.29   
1             2.65        2.76                  0.26             1.28   
2             2.80        3.24                  0.30             2.81   
3             3.85        3.49                  0.24             2.18   
4             2.80        2.69                  0.39             1.82   
..             ...         ...                   ...              ...   
173           1.68        0.61                  0.52             1.06   
174           1.80        0.75                  0.43             1.41   
175           1.59        0.69                  0.43             1.35   
176           1.65        0.68                  0.53             1.46   
177           2.05        0.76                  0.56             1.35   

     Color intensity   Hue  OD280/OD315 of diluted wines  Proline  
0               5.64  1.04                          3.92     1065  
1               4.38  1.05                          3.40     1050  
2               5.68  1.03                          3.17     1185  
3               7.80  0.86                          3.45     1480  
4               4.32  1.04                          2.93      735  
..               ...   ...                           ...      ...  
173             7.70  0.64                          1.74      740  
174             7.30  0.70                          1.56      750  
175            10.20  0.59                          1.56      835  
176             9.30  0.60                          1.62      840  
177             9.20  0.61                          1.60      560  

[178 rows x 14 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Label                         178 non-null    int64  
 1   Alcohol                       178 non-null    float64
 2   Malic Acid                    178 non-null    float64
 3   Ash                           178 non-null    float64
 4   Alcalinity of ash             178 non-null    float64
 5   Magnesium                     178 non-null    int64  
 6   Total phenols                 178 non-null    float64
 7   Flavanoids                    178 non-null    float64
 8   Nonflavanoid phenols          178 non-null    float64
 9   Proanthocyanins               178 non-null    float64
 10  Color intensity               178 non-null    float64
 11  Hue                           178 non-null    float64
 12  OD280/OD315 of diluted wines  178 non-null    float64
 13  Proli

In [ ]:
data.isnull()

Label  Alcohol  Malic Acid    Ash  Alcalinity of ash   Magnesium  \
0    False    False       False  False               False      False   
1    False    False       False  False               False      False   
2    False    False       False  False               False      False   
3    False    False       False  False               False      False   
4    False    False       False  False               False      False   
..     ...      ...         ...    ...                 ...        ...   
173  False    False       False  False               False      False   
174  False    False       False  False               False      False   
175  False    False       False  False               False      False   
176  False    False       False  False               False      False   
177  False    False       False  False               False      False   

     Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
0            False       False                 False            False   
1            False       False                 False            False   
2            False       False                 False            False   
3            False       False                 False            False   
4            False       False                 False            False   
..             ...         ...                   ...              ...   
173          False       False                 False            False   
174          False       False                 False            False   
175          False       False                 False            False   
176          False       False                 False            False   
177          False       False                 False            False   

     Color intensity    Hue  OD280/OD315 of diluted wines  Proline  
0              False  False                         False    False  
1              False  False                         False    False  
2              False  False                         False    False  
3              False  False                         False    False  
4              False  False                         False    False  
..               ...    ...                           ...      ...  
173            False  False                         False    False  
174            False  False                         False    False  
175            False  False                         False    False  
176            False  False                         False    False  
177            False  False                         False    False  

[178 rows x 14 columns]

In [ ]:
data.isnull().count()

Label                           178
Alcohol                         178
Malic Acid                      178
Ash                             178
Alcalinity of ash               178
Magnesium                       178
Total phenols                   178
Flavanoids                      178
Nonflavanoid phenols            178
Proanthocyanins                 178
Color intensity                 178
Hue                             178
OD280/OD315 of diluted wines    178
Proline                         178
dtype: int64

In [ ]:
data.describe()

Label     Alcohol  Malic Acid         Ash  Alcalinity of ash   \
count  178.000000  178.000000  178.000000  178.000000          178.000000   
mean     1.938202   13.000618    2.336348    2.366517           19.494944   
std      0.775035    0.811827    1.117146    0.274344            3.339564   
min      1.000000   11.030000    0.740000    1.360000           10.600000   
25%      1.000000   12.362500    1.602500    2.210000           17.200000   
50%      2.000000   13.050000    1.865000    2.360000           19.500000   
75%      3.000000   13.677500    3.082500    2.557500           21.500000   
max      3.000000   14.830000    5.800000    3.230000           30.000000   

        Magnesium  Total phenols  Flavanoids  Nonflavanoid phenols  \
count  178.000000     178.000000  178.000000            178.000000   
mean    99.741573       2.295112    2.029270              0.361854   
std     14.282484       0.625851    0.998859              0.124453   
min     70.000000       0.980000    0.340000              0.130000   
25%     88.000000       1.742500    1.205000              0.270000   
50%     98.000000       2.355000    2.135000              0.340000   
75%    107.000000       2.800000    2.875000              0.437500   
max    162.000000       3.880000    5.080000              0.660000   

       Proanthocyanins  Color intensity         Hue  \
count       178.000000       178.000000  178.000000   
mean          1.590899         5.058090    0.957449   
std           0.572359         2.318286    0.228572   
min           0.410000         1.280000    0.480000   
25%           1.250000         3.220000    0.782500   
50%           1.555000         4.690000    0.965000   
75%           1.950000         6.200000    1.120000   
max           3.580000        13.000000    1.710000   

       OD280/OD315 of diluted wines      Proline  
count                    178.000000   178.000000  
mean                       2.611685   746.893258  
std                        0.709990   314.907474  
min                        1.270000   278.000000  
25%                        1.937500   500.500000  
50%                        2.780000   673.500000  
75%                        3.170000   985.000000  
max                        4.000000  1680.000000

In [ ]:
#Extract the values
X=data.iloc[:,1:14].values
y=data.iloc[:,0].values

In [ ]:
# Creta train

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [ ]:
#Apply Stand Sclae
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [ ]:
X_train

array([[ 0.87668336,  0.79842885,  0.64412971, ...,  0.0290166 ,
        -1.06412236, -0.2059076 ],
       [-0.36659076, -0.7581304 , -0.39779858, ...,  0.0290166 ,
        -0.73083231, -0.81704676],
       [-1.69689407, -0.34424759, -0.32337513, ...,  0.90197362,
         0.51900537, -1.31256499],
       ...,
       [-0.70227477, -0.68615078, -0.65828065, ...,  0.46549511,
         0.51900537, -1.31256499],
       [ 1.13777093, -0.62316862, -0.91876272, ..., -0.18922266,
         1.03282752,  0.80164614],
       [ 1.4610222 ,  0.12361993,  0.42085937, ..., -1.45501034,
        -1.2168803 , -0.2719767 ]])

In [ ]:
# Apply PCA
from sklearn.decomposition import PCA
pca=PCA(n_components=None)#13
X_train=pca.fit_transform(X_train)
X_test=pca.transform(X_test)
print('PCA Applied')

PCA Applied


In [ ]:
explained_variance=pca.explained_variance_ratio_
explained_variance

array([0.36884109, 0.19318394, 0.10752862, 0.07421996, 0.06245904,
       0.04909   , 0.04117287, 0.02495984, 0.02308855, 0.01864124,
       0.01731766, 0.01252785, 0.00696933])

In [ ]:
explained_variance.cumsum()

array([0.36884109, 0.56202504, 0.66955366, 0.74377362, 0.80623266,
       0.85532266, 0.89649554, 0.92145537, 0.94454392, 0.96318516,
       0.98050282, 0.99303067, 1.        ])

In [ ]:
pca.get_feature_names_out()

array(['pca0', 'pca1', 'pca2', 'pca3', 'pca4', 'pca5', 'pca6', 'pca7',
       'pca8', 'pca9', 'pca10', 'pca11', 'pca12'], dtype=object)

In [ ]:
X_train

array([[-2.17884511, -1.07218467,  0.07256566, ...,  0.1271222 ,
        -0.07901204,  0.4542412 ],
       [-1.80819239,  1.57822344,  0.00896477, ..., -0.96074782,
        -0.40434955, -0.34098912],
       [ 1.09829474,  2.22124345, -0.1093294 , ...,  1.10392771,
         0.10693966,  0.36900172],
       ...,
       [ 0.01097276,  1.99585453, -0.57933999, ..., -0.11109947,
        -0.01706346, -0.33083897],
       [ 2.89176687, -0.77155548,  1.10218748, ...,  0.13302355,
        -0.17318731, -0.22802702],
       [-2.44830439, -2.11360296,  0.79001847, ..., -0.49170902,
         0.15199135,  0.3013311 ]])

In [ ]:
X_train.shape

(142, 13)

In [ ]:
# Apply PCA
from sklearn.decomposition import PCA
pca=PCA(n_components=7)#13
X_train=pca.fit_transform(X_train)
X_test=pca.transform(X_test)
print('PCA Applied')

PCA Applied


In [ ]:
explained_variance=pca.explained_variance_ratio_
explained_variance

array([0.36884109, 0.19318394, 0.10752862, 0.07421996, 0.06245904,
       0.04909   , 0.04117287])

In [ ]:
explained_variance.cumsum()

array([0.36884109, 0.56202504, 0.66955366, 0.74377362, 0.80623266,
       0.85532266, 0.89649554])

In [ ]:
X_train.shape

(142, 7)

In [ ]:
pca.get_feature_names_out()

array(['pca0', 'pca1', 'pca2', 'pca3', 'pca4', 'pca5', 'pca6'],
      dtype=object)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(X_train,y_train)
y_pred=dt.predict(X_test)
y_pred
y_pred_train=dt.predict(X_train)



In [ ]:
from sklearn.metrics import classification_report,accuracy_score
print(classification_report(y_test,y_pred))
print('Test Accuracy',accuracy_score(y_test,y_pred))


              precision    recall  f1-score   support

           1       0.00      0.00      0.00        14
           2       0.44      1.00      0.62        16
           3       0.00      0.00      0.00         6

    accuracy                           0.44        36
   macro avg       0.15      0.33      0.21        36
weighted avg       0.20      0.44      0.27        36

Test Accuracy 0.4444444444444444


C:\Users\vijay\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\vijay\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\vijay\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
# log_reg, svm,knn,rf,dt,boosting
from sklearn.svm import SVC
svm=SVC()
svm.fit(X_train,y_train)
y_pred=svm.predict(X_test)
y_pred
y_pred_train=svm.predict(X_train)
y_pred_train
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00        14
           2       0.44      1.00      0.62        16
           3       0.00      0.00      0.00         6

    accuracy                           0.44        36
   macro avg       0.15      0.33      0.21        36
weighted avg       0.20      0.44      0.27        36



C:\Users\vijay\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\vijay\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\vijay\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
